-- Manual v4 Phase 2 amendment, 2026-10-02 (owner direction; ADR-011).
-- 1. The vocabulary grows from 35 to 115 tags, generated from contracts/skills.yaml.
INSERT INTO skill_vocabulary (tag, display, parent, requires_licence) VALUES
  ('locs', 'Locs', 'hair', FALSE),
  ('hair_coloring', 'Hair coloring', 'hair', FALSE),
  ('natural_hair', 'Natural hair care', 'hair', FALSE),
  ('kids_haircut', 'Kids haircut', 'hair', FALSE),
  ('waxing', 'Waxing', 'beauty', FALSE),
  ('facials', 'Facials', 'beauty', TRUE),
  ('spray_tan', 'Spray tan', 'beauty', FALSE),
  ('henna', 'Henna', 'beauty', FALSE),
  ('tattoo', 'Tattoo', 'beauty', TRUE),
  ('piercing', 'Piercing', 'beauty', TRUE),
  ('appliance_repair', 'Appliance repair', 'repair', FALSE),
  ('watch_repair', 'Watch repair', 'repair', FALSE),
  ('jewelry_repair', 'Jewelry repair', 'repair', FALSE),
  ('console_repair', 'Game console repair', 'tech', FALSE),
  ('tablet_repair', 'Tablet repair', 'tech', FALSE),
  ('data_recovery', 'Data recovery', 'tech', FALSE),
  ('tech_support', 'Tech support', 'tech', FALSE),
  ('smart_home_setup', 'Smart home setup', 'tech', FALSE),
  ('instrument_repair', 'Instrument repair', 'repair', FALSE),
  ('upholstery', 'Upholstery', 'repair', FALSE),
  ('carpet_cleaning', 'Carpet cleaning', 'home', FALSE),
  ('window_cleaning', 'Window cleaning', 'home', FALSE),
  ('pressure_washing', 'Pressure washing', 'home', FALSE),
  ('gutter_cleaning', 'Gutter cleaning', 'home', FALSE),
  ('junk_removal', 'Junk removal', 'home', FALSE),
  ('drywall', 'Drywall', 'home', FALSE),
  ('flooring', 'Flooring', 'home', FALSE),
  ('carpentry', 'Carpentry', 'home', FALSE),
  ('fencing', 'Fencing', 'home', FALSE),
  ('landscaping', 'Landscaping', 'home', FALSE),
  ('tree_service', 'Tree service', 'home', FALSE),
  ('snow_removal', 'Snow removal', 'home', FALSE),
  ('pool_cleaning', 'Pool cleaning', 'home', FALSE),
  ('pest_control', 'Pest control', 'home', TRUE),
  ('hvac', 'Heating and air conditioning', 'home', TRUE),
  ('plumbing_major', 'Plumbing (licensed)', 'home', TRUE),
  ('roofing', 'Roofing', 'home', TRUE),
  ('garage_door', 'Garage door repair', 'home', FALSE),
  ('home_organizing', 'Home organizing', 'home', FALSE),
  ('interior_design', 'Interior design', 'home', FALSE),
  ('laundry', 'Laundry and ironing', 'home', FALSE),
  ('house_sitting', 'House sitting', 'home', FALSE),
  ('welding', 'Welding', 'home', FALSE),
  ('mobile_mechanic', 'Mobile mechanic', 'vehicle', FALSE),
  ('tire_service', 'Tire service', 'vehicle', FALSE),
  ('car_detailing', 'Car detailing', 'vehicle', FALSE),
  ('motorcycle_repair', 'Motorcycle repair', 'vehicle', FALSE),
  ('car_audio', 'Car audio', 'vehicle', FALSE),
  ('dj', 'DJ', 'events', FALSE),
  ('event_planning', 'Event planning', 'events', FALSE),
  ('party_decor', 'Party decor', 'events', FALSE),
  ('catering', 'Catering', 'food', FALSE),
  ('personal_chef', 'Personal chef', 'food', FALSE),
  ('baking', 'Cakes and baking', 'food', FALSE),
  ('bartending', 'Bartending', 'events', FALSE),
  ('videography', 'Videography', 'creative', FALSE),
  ('face_painting', 'Face painting', 'events', FALSE),
  ('mc_host', 'MC and host', 'events', FALSE),
  ('graphic_design', 'Graphic design', 'creative', FALSE),
  ('web_design', 'Website design', 'creative', FALSE),
  ('video_editing', 'Video editing', 'creative', FALSE),
  ('photo_editing', 'Photo editing', 'creative', FALSE),
  ('social_media', 'Social media management', 'creative', FALSE),
  ('music_production', 'Music production', 'creative', FALSE),
  ('custom_printing', 'Custom printing', 'creative', FALSE),
  ('sewing', 'Custom sewing', 'creative', FALSE),
  ('language_lessons', 'Language lessons', 'lessons', FALSE),
  ('coding_lessons', 'Coding lessons', 'lessons', FALSE),
  ('dance_lessons', 'Dance lessons', 'lessons', FALSE),
  ('swim_lessons', 'Swimming lessons', 'lessons', FALSE),
  ('art_lessons', 'Art lessons', 'lessons', FALSE),
  ('driving_lessons', 'Driving lessons', 'lessons', TRUE),
  ('yoga', 'Yoga and pilates', 'wellness', FALSE),
  ('sports_coaching', 'Sports coaching', 'lessons', FALSE),
  ('pet_training', 'Pet training', 'pets', FALSE),
  ('courier', 'Courier and delivery', 'errands', FALSE),
  ('personal_shopping', 'Personal shopping', 'errands', FALSE),
  ('resume_writing', 'Resume writing', 'writing', FALSE),
  ('translation', 'Translation', 'writing', FALSE),
  ('proofreading', 'Proofreading and editing', 'writing', FALSE);

-- 2. Provider-described skills. A provider may keep a skill PLUG does not list. Its tag is
--    registered here under parent 'custom' so request_constraints keeps its foreign key; the
--    startup check compares skills.yaml with every tag whose parent is not 'custom'.
CREATE TABLE provider_custom_skills (
    user_id TEXT NOT NULL REFERENCES provider_profiles(user_id) ON DELETE CASCADE,
    tag TEXT NOT NULL REFERENCES skill_vocabulary(tag) CHECK (tag ~ '^custom_[a-z0-9_]{1,33}$'),
    label TEXT NOT NULL CHECK (length(label) BETWEEN 3 AND 40),
    keywords TEXT[] NOT NULL CHECK (cardinality(keywords) BETWEEN 1 AND 8),
    position SMALLINT NOT NULL CHECK (position BETWEEN 0 AND 4),
    PRIMARY KEY (user_id, tag)
);
CREATE INDEX provider_custom_skills_keywords ON provider_custom_skills USING GIN (keywords);
