#!/usr/bin/env node
// Reads design/tokens.json (the single source of truth, manual.docx §10.1) and
// writes design/generated/tokens.css and design/generated/Tokens.swift.
// No dependencies — run with the project's own Node: `node design/generate-tokens.mjs`.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const tokens = JSON.parse(readFileSync(join(here, "tokens.json"), "utf8"));
const outDir = join(here, "generated");
mkdirSync(outDir, { recursive: true });

function kebab(...parts) {
  return parts.join("-");
}

function resolveRef(value) {
  // "{color.line.200}" -> css var(--color-line-200)
  return String(value).replace(/\{([^}]+)\}/g, (_, path) => `var(--${path.split(".").join("-")})`);
}

// ---- tokens.css -----------------------------------------------------------
const cssLines = [
  "/* GENERATED by design/generate-tokens.mjs — do not hand-edit. Source: design/tokens.json */",
  ":root {",
];

for (const [group, scale] of Object.entries(tokens.color)) {
  for (const [step, value] of Object.entries(scale)) {
    cssLines.push(`  --color-${kebab(group, step)}: ${value};`);
  }
}
for (const [step, value] of Object.entries(tokens.space)) {
  cssLines.push(`  --space-${step}: ${value}px;`);
}
for (const [step, value] of Object.entries(tokens.radius)) {
  cssLines.push(`  --radius-${step}: ${value}px;`);
}
for (const [name, scale] of Object.entries(tokens.type)) {
  cssLines.push(`  --type-${name}-size: ${scale.size}px;`);
  cssLines.push(`  --type-${name}-line: ${scale.line}px;`);
  cssLines.push(`  --type-${name}-weight: ${scale.weight};`);
  cssLines.push(`  --type-${name}-tracking: ${scale.tracking}px;`);
}
cssLines.push(`  --motion-fast: ${tokens.motion.fast}ms;`);
cssLines.push(`  --motion-base: ${tokens.motion.base}ms;`);
cssLines.push(`  --motion-slow: ${tokens.motion.slow}ms;`);
cssLines.push(`  --motion-easing: ${tokens.motion.easing};`);
cssLines.push(`  --elevation-flat: ${resolveRef(tokens.elevation.flat)};`);
cssLines.push(`  --elevation-raised: ${tokens.elevation.raised};`);
cssLines.push(`  --target-min-touch: ${tokens.target.minTouch}px;`);
cssLines.push("}");
writeFileSync(join(outDir, "tokens.css"), cssLines.join("\n") + "\n");

// ---- Tokens.swift -----------------------------------------------------------
// iOS uses system typography (tokens.json._rules), so only color, space, radius
// and motion — the values that are not typographic — are generated for Swift.
function swiftColorHex(hex) {
  const clean = hex.replace("#", "");
  // Fully qualified: inside `enum Color { ... }` below, an unqualified `Color(...)`
  // resolves to that nested enum itself, not SwiftUI.Color — a self-shadowing trap.
  return `SwiftUI.Color(hex: "${clean}")`;
}

const swiftLines = [
  "// GENERATED by design/generate-tokens.mjs — do not hand-edit. Source: design/tokens.json",
  "import SwiftUI",
  "",
  "enum PlugTokens {",
  "    enum Color {",
];
for (const [group, scale] of Object.entries(tokens.color)) {
  for (const [step, value] of Object.entries(scale)) {
    const name = kebab(group, step).replace(/-([a-zA-Z0-9])/g, (_, c) => c.toUpperCase());
    swiftLines.push(`        static let ${name} = ${swiftColorHex(value)}`);
  }
}
swiftLines.push("    }");
swiftLines.push("    enum Space {");
for (const [step, value] of Object.entries(tokens.space)) {
  swiftLines.push(`        static let s${step}: CGFloat = ${value}`);
}
swiftLines.push("    }");
swiftLines.push("    enum Radius {");
for (const [step, value] of Object.entries(tokens.radius)) {
  swiftLines.push(`        static let ${step}: CGFloat = ${value}`);
}
swiftLines.push("    }");
swiftLines.push("    enum Motion {");
swiftLines.push(`        static let fast: Double = ${tokens.motion.fast} / 1000`);
swiftLines.push(`        static let base: Double = ${tokens.motion.base} / 1000`);
swiftLines.push(`        static let slow: Double = ${tokens.motion.slow} / 1000`);
swiftLines.push("    }");
swiftLines.push("    static let minTouchTarget: CGFloat = " + tokens.target.minTouch);
swiftLines.push("}");
writeFileSync(join(outDir, "Tokens.swift"), swiftLines.join("\n") + "\n");

console.log(`Wrote ${join(outDir, "tokens.css")} and ${join(outDir, "Tokens.swift")}`);
