#!/usr/bin/env node
// Reads design/tokens.json (the single source of truth, manual.docx §10.1) and
// writes design/generated/tokens.css and design/generated/Tokens.swift.
// No dependencies — run with the project's own Node: `node design/generate-tokens.mjs`.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const tokens = JSON.parse(readFileSync(join(here, "tokens.json"), "utf8"));
// Transitional v3 names for frozen Phase 0/1 code (manual v4 §10). Each resolves to a v4 token.
const aliases = JSON.parse(readFileSync(join(here, "token-aliases.json"), "utf8"));
// A colour group is either one value ("paper") or a scale ("ink": {"900": ...}).
const colorEntries = () => Object.entries(tokens.color).flatMap(([group, scale]) =>
  typeof scale === "string" ? [[[group], scale]] : Object.entries(scale).map(([step, value]) => [[group, step], value]));
const typeEntries = () => Object.entries(tokens.type).filter(([name]) => name !== "family");
const camel = (parts) => kebab(...parts).replace(/-([a-zA-Z0-9])/g, (_, c) => c.toUpperCase());
const outDir = join(here, "generated");
mkdirSync(outDir, { recursive: true });

function kebab(...parts) {
  return parts.join("-");
}

function resolveRef(value) {
  // "{color.line.200}" -> css var(--color-line-200)
  return String(value).replace(/\{([^}]+)\}/g, (_, path) => `var(--${path.split(".").join("-")})`);
}

// ---- tokens.css -----------------------------------------------------------
const cssLines = [
  "/* GENERATED by design/generate-tokens.mjs — do not hand-edit. Source: design/tokens.json */",
  ":root {",
];

for (const [parts, value] of colorEntries()) {
  cssLines.push(`  --color-${kebab(...parts)}: ${value};`);
}
for (const [step, value] of Object.entries(tokens.space)) {
  cssLines.push(`  --space-${step}: ${value}px;`);
}
for (const [step, value] of Object.entries(tokens.radius)) {
  cssLines.push(`  --radius-${step}: ${value}px;`);
}
cssLines.push(`  --font-sans: ${tokens.type.family.web};`);
cssLines.push(`  --font-mono: ${tokens.type.family.mono};`);
for (const [name, scale] of typeEntries()) {
  cssLines.push(`  --type-${name}-size: ${scale.size}px;`);
  cssLines.push(`  --type-${name}-line: ${scale.line}px;`);
  cssLines.push(`  --type-${name}-weight: ${scale.weight};`);
  cssLines.push(`  --type-${name}-tracking: ${scale.tracking}px;`);
}
cssLines.push(`  --motion-fast: ${tokens.motion.fast}ms;`);
cssLines.push(`  --motion-base: ${tokens.motion.base}ms;`);
cssLines.push(`  --motion-slow: ${tokens.motion.slow}ms;`);
cssLines.push(`  --motion-easing: ${tokens.motion.easing};`);
cssLines.push(`  --elevation-flat: ${resolveRef(tokens.elevation.flat)};`);
cssLines.push(`  --elevation-raised: ${tokens.elevation.raised};`);
cssLines.push(`  --target-min-touch: ${tokens.target.minTouch}px;`);
cssLines.push("  /* Transitional v3 aliases for frozen phases (design/token-aliases.json). */");
for (const [name, ref] of Object.entries(aliases.color)) {
  cssLines.push(`  --color-${name.replace(/([A-Z])/g, "-$1").replace(/([a-z])([0-9])/g, "$1-$2").toLowerCase()}: var(--color-${ref.split(".").join("-")});`);
}
for (const [name, ref] of Object.entries(aliases.radius)) {
  cssLines.push(`  --radius-${name}: var(--radius-${ref});`);
}
cssLines.push("}");
writeFileSync(join(outDir, "tokens.css"), cssLines.join("\n") + "\n");

// ---- Tokens.swift -----------------------------------------------------------
// iOS uses system typography (tokens.json._rules), so only color, space, radius
// and motion are generated alongside base type sizes; SwiftUI scales type dynamically.
function swiftColorHex(hex) {
  const clean = hex.replace("#", "");
  // Fully qualified: inside `enum Color { ... }` below, an unqualified `Color(...)`
  // resolves to that nested enum itself, not SwiftUI.Color — a self-shadowing trap.
  return `SwiftUI.Color(hex: "${clean}")`;
}

const swiftLines = [
  "// GENERATED by design/generate-tokens.mjs — do not hand-edit. Source: design/tokens.json",
  "import SwiftUI",
  "",
  "enum PlugTokens {",
  "    enum Color {",
];
for (const [parts, value] of colorEntries()) {
  swiftLines.push(`        static let ${camel(parts)} = ${swiftColorHex(value)}`);
}
swiftLines.push("        // Transitional v3 names for frozen Phase 0/1 code (design/token-aliases.json).");
for (const [name, ref] of Object.entries(aliases.color)) {
  swiftLines.push(`        static let ${name} = ${camel(ref.split("."))}`);
}
swiftLines.push("    }");
swiftLines.push("    enum Space {");
for (const [step, value] of Object.entries(tokens.space)) {
  swiftLines.push(`        static let s${step}: CGFloat = ${value}`);
}
swiftLines.push("    }");
swiftLines.push("    enum Radius {");
for (const [step, value] of Object.entries(tokens.radius)) {
  swiftLines.push(`        static let ${step}: CGFloat = ${value}`);
}
for (const [name, ref] of Object.entries(aliases.radius)) {
  swiftLines.push(`        static let ${name}: CGFloat = ${ref}`);
}
swiftLines.push("    }");
swiftLines.push("    enum TypeSize {");
for (const [name, value] of typeEntries()) {
  swiftLines.push(`        static let ${name}: CGFloat = ${value.size}`);
}
swiftLines.push("    }");
swiftLines.push("    enum Motion {");
swiftLines.push(`        static let fast: Double = ${tokens.motion.fast} / 1000`);
swiftLines.push(`        static let base: Double = ${tokens.motion.base} / 1000`);
swiftLines.push(`        static let slow: Double = ${tokens.motion.slow} / 1000`);
swiftLines.push("    }");
swiftLines.push("    static let minTouchTarget: CGFloat = " + tokens.target.minTouch);
swiftLines.push("}");
writeFileSync(join(outDir, "Tokens.swift"), swiftLines.join("\n") + "\n");

console.log(`Wrote ${join(outDir, "tokens.css")} and ${join(outDir, "Tokens.swift")}`);
